package entity;
// Generated 12-ene-2018 9:51:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Votante generated by hbm2java
 */
public class Votante  implements java.io.Serializable {


     private int idVotante;
     private int docVotante;
     private String nombreVotante;
     private Set<Votacion> votacions = new HashSet<Votacion>(0);

    public Votante() {
    }

	
    public Votante(int idVotante, int docVotante, String nombreVotante) {
        this.idVotante = idVotante;
        this.docVotante = docVotante;
        this.nombreVotante = nombreVotante;
    }
    public Votante(int idVotante, int docVotante, String nombreVotante, Set<Votacion> votacions) {
       this.idVotante = idVotante;
       this.docVotante = docVotante;
       this.nombreVotante = nombreVotante;
       this.votacions = votacions;
    }
   
    public int getIdVotante() {
        return this.idVotante;
    }
    
    public void setIdVotante(int idVotante) {
        this.idVotante = idVotante;
    }
    public int getDocVotante() {
        return this.docVotante;
    }
    
    public void setDocVotante(int docVotante) {
        this.docVotante = docVotante;
    }
    public String getNombreVotante() {
        return this.nombreVotante;
    }
    
    public void setNombreVotante(String nombreVotante) {
        this.nombreVotante = nombreVotante;
    }
    public Set<Votacion> getVotacions() {
        return this.votacions;
    }
    
    public void setVotacions(Set<Votacion> votacions) {
        this.votacions = votacions;
    }




}


