package entity;
// Generated 12-ene-2018 9:51:50 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Votacion generated by hbm2java
 */
public class Votacion  implements java.io.Serializable {


     private int idVotacion;
     private Candidato candidato;
     private Votante votante;
     private Date fechaVotacion;

    public Votacion() {
    }

    public Votacion(int idVotacion,Candidato candidato, Votante votante, Date fechaVotacion) {
       this.idVotacion = idVotacion;
       this.candidato = candidato;
       this.votante = votante;
       this.fechaVotacion = fechaVotacion;
    }
   
    public int getIdVotacion() {
        return this.idVotacion;
    }
    
    public void setIdVotacion(int idVotacion) {
        this.idVotacion = idVotacion;
    }
    public Candidato getCandidato() {
        return this.candidato;
    }
    
    public void setCandidatoCandidato(Candidato candidato) {
        this.candidato = candidato;
    }
    public Votante getVotante() {
        return this.votante;
    }
    
    public void setVotante(Votante votante) {
        this.votante = votante;
    }
    public Date getFechaVotacion() {
        return this.fechaVotacion;
    }
    
    public void setFechaVotacion(Date fechaVotacion) {
        this.fechaVotacion = fechaVotacion;
    }




}


